let config={};let entities=[];const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
async function api(url,opt){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...opt});const d=await r.json();if(!r.ok)throw Error(d.error||'Erreur');return d}
function toast(t){const x=$('#toast');x.textContent=t;x.style.display='block';clearTimeout(window.tt);window.tt=setTimeout(()=>x.style.display='none',2200)}
async function load(){config=await api('/api/config/raw');$('#haUrl').value=config.homeAssistant?.url||'';$('#haToken').value=config.homeAssistant?.token||'';try{entities=await api('/api/entities')}catch{entities=[]}render()}
function save(){return api('/api/config',{method:'PUT',body:JSON.stringify(config)}).then(()=>toast('Configuration enregistrée'))}
function picker(value,domains=''){const list=entities.filter(e=>!domains||domains.split(',').includes(e.domain));return `<input value="${esc(value)}" data-entity-input placeholder="entity_id (ex: light.salon)"><div class="entity-picker">${list.slice(0,18).map(e=>`<button type="button" data-pick="${esc(e.entity_id)}">${esc(e.friendly_name)}<br><span class="muted">${esc(e.entity_id)} · ${esc(e.state)}</span></button>`).join('')}</div>`}
function open(title,html,onSave){$('#modalTitle').textContent=title;$('#form').innerHTML=html;$('#modal').classList.remove('hidden');document.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{const i=b.closest('.field-wrap')?.querySelector('[data-entity-input]')||document.querySelector('[data-entity-input]');if(i)i.value=b.dataset.pick});$('#form').onsubmit=e=>{e.preventDefault();onSave(new FormData(e.target));$('#modal').classList.add('hidden');save()}}
function field(label,name,value='',wide=false,type='text'){return `<label class="${wide?'wide':''}">${label}<input name="${name}" type="${type}" value="${esc(value)}"></label>`}
function render(){renderWidgets();renderProfiles();renderVehicle();renderScenes()}
function renderWidgets(){const w=config.widgets||[];$('#widgets').innerHTML=w.map((x,i)=>`<div class="row"><div><b>${esc(x.icon||'▦')} ${esc(x.name)}</b><div class="muted">${esc(x.type)} · ${esc(x.entity||x.url||'sans source')}</div></div><div class="actions"><button class="ghost" data-edit-widget="${i}">Modifier</button><button class="danger" data-del-widget="${i}">Supprimer</button></div></div>`).join('')||'<span class="muted">Aucun widget personnalisé.</span>';document.querySelectorAll('[data-edit-widget]').forEach(b=>b.onclick=()=>editWidget(+b.dataset.editWidget));document.querySelectorAll('[data-del-widget]').forEach(b=>b.onclick=()=>{config.widgets.splice(+b.dataset.delWidget,1);save().then(render)})}
function editWidget(i=-1){const x=i>=0?config.widgets[i]:{name:'Nouvel appareil',type:'light',entity:'',icon:'💡',size:'normal',url:'',iframe:'',attribute:''};const types=['light','switch','climate','cover','fan','sensor','binary_sensor','media_player','camera','button','scene','iframe'];open(i<0?'Ajouter un appareil':'Modifier l’appareil',`<div class="form-grid">${field('Nom','name',x.name)}<label>Type<select name="type">${types.map(v=>`<option ${x.type===v?'selected':''}>${v}</option>`).join('')}</select></label>${field('Entity ID','entity',x.entity,true)}${field('Icône','icon',x.icon)}<label>Taille<select name="size"><option value="normal">Normal</option><option value="wide" ${x.size==='wide'?'selected':''}>Large</option><option value="tall" ${x.size==='tall'?'selected':''}>Grande hauteur</option><option value="full" ${x.size==='full'?'selected':''}>Plein écran</option></select></label>${field('URL iframe / site','url',x.url||x.iframe||'',true)}${field('Image / URL (optionnel)','image',x.image||'',true)}${field('Attribut affiché (optionnel)','attribute',x.attribute||'',true)}<p class="muted wide">Pour un iframe, colle uniquement l’URL <b>src</b>. Exemple Sketchfab : https://sketchfab.com/models/.../embed?autospin=1&autostart=1&preload=1&transparent=1</p></div><button class="primary submit">Enregistrer l’appareil</button>`,f=>{const n={...x,name:f.get('name'),type:f.get('type'),entity:f.get('entity'),icon:f.get('icon'),size:f.get('size'),url:f.get('url'),iframe:f.get('url'),image:f.get('image'),attribute:f.get('attribute')};if(i<0)config.widgets.push(n);else config.widgets[i]=n;render()})}
function renderProfiles(){const p=config.profiles||[];$('#profiles').innerHTML=p.map((x,i)=>`<div class="row"><div><b>${esc(x.name)}</b><div class="muted">${esc(x.entity||'person non configurée')} · batterie ${esc(x.battery||'—')}</div></div><button class="ghost" data-edit-profile="${i}">Modifier</button></div>`).join('');document.querySelectorAll('[data-edit-profile]').forEach(b=>b.onclick=()=>editProfile(+b.dataset.editProfile))}
function editProfile(i){const x=config.profiles[i];open('Modifier le profil',`<div class="form-grid">${field('Nom','name',x.name)}${field('Entity présence','entity',x.entity,true)}${field('Entity batterie','battery',x.battery,true)}${field('Avatar URL','avatar',x.avatar,true)}${field('Image si HOME','home',x.states?.home||'',true)}${field('Image si ABSENT','not_home',x.states?.not_home||'',true)}${field('Image si TRAVAIL','work',x.states?.work||'',true)}${field('Image si CONDUITE','driving',x.states?.driving||'',true)}</div><button class="primary submit">Enregistrer</button>`,f=>{x.name=f.get('name');x.entity=f.get('entity');x.battery=f.get('battery');x.avatar=f.get('avatar');x.states={home:f.get('home'),not_home:f.get('not_home'),work:f.get('work'),driving:f.get('driving')};render()})}
function renderVehicle(){const x=config.vehicle||{};$('#vehicle').innerHTML=`<div class="row"><div><b>${esc(x.name||'Véhicule')}</b><div class="muted">${esc(x.model||'Modèle non défini')} · ${x.iframe?'iframe 3D configuré':'pas de modèle 3D'}</div></div><button class="ghost" id="editVehicle">Modifier</button></div>`;$('#editVehicle').onclick=()=>{open('Modifier le véhicule',`<div class="form-grid">${field('Nom','name',x.name)}${field('Modèle','model',x.model)}${field('Iframe 3D / Sketchfab URL','iframe',x.iframe||'',true)}${field('Image / URL modèle','image',x.image||'',true)}${field('Verrouillage','lock',x.lock,true)}${field('Carburant %','fuel',x.fuel)}${field('Batterie %','battery',x.battery)}${field('Autonomie km','range',x.range)}${field('Pneu AVG','tireFrontLeft',x.tireFrontLeft)}${field('Pneu AVD','tireFrontRight',x.tireFrontRight)}${field('Pneu ARG','tireRearLeft',x.tireRearLeft)}${field('Pneu ARD','tireRearRight',x.tireRearRight)}<label class="check wide"><input type="checkbox" name="enabled" ${x.enabled?'checked':''}> Afficher le véhicule</label></div><button class="primary submit">Enregistrer</button>`,f=>{Object.keys(x).forEach(k=>{if(f.has(k))x[k]=f.get(k)});x.enabled=f.get('enabled')==='on';render()})}}
function renderScenes(){const s=config.scenes||[];$('#scenes').innerHTML=s.map((x,i)=>`<div class="row"><div><b>${esc(x.icon)} ${esc(x.name)}</b><div class="muted">${esc(x.entity||'scene non configurée')}</div></div><div class="actions"><button class="ghost" data-edit-scene="${i}">Modifier</button><button class="danger" data-del-scene="${i}">Supprimer</button></div></div>`).join('');document.querySelectorAll('[data-edit-scene]').forEach(b=>b.onclick=()=>editScene(+b.dataset.editScene));document.querySelectorAll('[data-del-scene]').forEach(b=>b.onclick=()=>{config.scenes.splice(+b.dataset.delScene,1);save().then(render)})}
function editScene(i=-1){const x=i<0?{name:'Nouvelle scène',icon:'⚡',entity:''}:config.scenes[i];open(i<0?'Ajouter une scène':'Modifier la scène',`<div class="form-grid">${field('Nom','name',x.name)}${field('Icône','icon',x.icon)}${field('Entity scene','entity',x.entity,true)}</div><button class="primary submit">Enregistrer</button>`,f=>{Object.assign(x,{name:f.get('name'),icon:f.get('icon'),entity:f.get('entity')});if(i<0)config.scenes.push(x);render()})}
$('#addWidget').onclick=()=>editWidget();$('#addScene').onclick=()=>editScene();$('#close').onclick=()=>$('#modal').classList.add('hidden');$('#saveConnection').onclick=async()=>{config.homeAssistant.url=$('#haUrl').value.trim();config.homeAssistant.token=$('#haToken').value.trim();await save();try{entities=await api('/api/entities');toast('Connexion Home Assistant OK')}catch(e){toast('Connexion impossible: '+e.message)}};$('#test').onclick=async()=>{try{await api('/api/test',{method:'POST'});toast('Home Assistant est accessible')}catch(e){toast('Échec: '+e.message)}};load();
